##  Java 异常类层次结构图
![Java异常类层次结构图](https://note.youdao.com/yws/public/resource/443915cbe32b82c13708e64cb87b94c1/xmlnote/162299FE2B6A486C93E087238CA921FF/12484)
- Exception和 Error， ⼆者都是 Java异常处理的重要⼦类， 各⾃都包含⼤量⼦类，均继承自Throwable类
- Error表⽰系统级的错误， 是java运⾏环境内部错误或者硬件问题， 不能指望程序来处理这样的问题， 除了退出运⾏外别⽆选择， 它是Java虚拟机抛出的
- Exception 表⽰程序需要捕捉、 需要处理的常， 是由与程序设计的不完善⽽出现的问题， 程序必须处理的问题

## Error
- Error是指在正常情况下不太可能出现的错误，它`与代码的编写`无关，通常是表示运行时JVM出现的问题，比如系统内部错误、或者资源不足等，这些异常发生时，Java 虚拟机（JVM）一般会选择`线程终止`
- 常见的有： OutOfMemoryError（ 内存溢出 ） 、 VirtualMachineError（虚拟机错误）、 NoClassDefFoundError（类定义错误）

## Exception
### 可检查异常 （Exception）
- 需要我们在程序中`必须`进行显式的捕获处理，否则将会`编译报错`
- 常见的有IOException、SQLException

### 不可检查异常 （ RuntimeException ）
- 程序本身`不要求`我们强制去捕获处理，但是可以`避免`代码在运行过程中的逻辑错误
- 常见的有NullPointerException（空指针）、ArrayIndexOutOfBoundException（下标越界异常）

## 异常处理注意事项
### 谨慎使用异常处理
- try..catch会造成程序的`额外开销`，所以建议只捕获关键的代码，切忌`不要用try包住一个很大的代码块`
- Java每实例化一个Exception，就会`对当时的栈进行快照`，如果操作比较频繁，那么对资源的开销就不能被忽略

## try和finally
### finally的执行顺序
- 当在 try 块或 catch 块中遇到 return语句时，finally 语句块将在`方法返回之前被执行`

### finally和try都有return
- 如果try，finally语句里均有return，`忽略try的return，而使用finally的return`
- `建议finally不要带return`


### 如果在finally里面对将要return的变量做了修改，返回的是修改后的值吗
- 如果返回的是引用类型，修改有效
- 如果返回的不是引用类型的，修改无效


    // 测试 修改值类型
    static int f() {
        int ret = 0;
        try {
        	// 返回 0，finally内的修改效果不起作用
            return ret;  
        } finally {
            ret++;
            System.out.println("finally执行");
        }
    }
    
    // 测试 修改引用类型
    static int[] f2(){
        int[] ret = new int[]{0};
        try {
        	// 返回 [1]，finally内的修改效果起了作用
            return ret;  
        } finally {
            ret[0]++;
            System.out.println("finally执行");
        }
    }

### finally 块不会被执行的情况
1. 在 finally 语句块第一行发生了异常。 因为在其他行，finally 块还是会得到执行
2. 在前面的代码中用了 System.exit(int)已退出程序。 exit 是带参函数 ；若该语句在异常语句之后，finally 会执行
3. 程序所在的线程死亡
4. 关闭 CPU